verion: '3'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    port:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    port:
      - '27017:27017'